name: Compile PDF

# Run on push to main
on:
  push:
    branches:
      - main

jobs:
  compile:
    name: Compile PDF via xelatex
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install LaTeX (xelatex and biber)
        run: sudo apt-get update && sudo apt-get install texlive-xetex biber

      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Compile PDF
        run: ./compile.sh

      - name: Store PDF as artifact
        uses: actions/upload-artifact@v4.1.0
        with:
          name: thesis-pdf
          path: ./fau-thesis.pdf

  publish:
    name: Publish PDF to Google Drive
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Load PDF artifact
        uses: actions/download-artifact@v4.1.1
        with:
          name: thesis-pdf

      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@v0.3
        with:
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          filename: "fau-thesis.pdf"
          folderId: ${{ secrets.FOLDER_ID }}
          name: "Integration of Gaia-X in Carecentive (Working Snapshot).pdf"
          overwrite: "true"
